[package]
name = "phoenix-multisig-deployer"
version = { workspace = true }
authors = ["Jakub <jakub@moonbite.space", "Kaloyan <kaloyan@moonbite.space"]
repository = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[lib]
crate-type = ["cdylib"]

[features]
testutils = ["soroban-sdk/testutils"]

[dependencies]
soroban-sdk = { workspace = true }

[dev_dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
